name: agro_connect
description: "An e-commerce grocery shopping platform that connect customers with the farmers directly, to avoid the middlemen and the price inflation of products."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/fruit_basket.svg'
    - 'assets/images/farmers_market.svg'
    - 'assets/images/ontime_delivery.svg'
